
title: "Enrico Maria Bufacchi [SITO IN MANUTENZIONE. MOLTI PDF NON SARANNO MOMENTANEAMENTE DISPONIBILI]"
email: "enrico03.bufacchi@gmail.com" 
description: "Studente di matematica teorica, scrittore, saggista, teorico."
url: "http://enricomariabufacchi.it"
baseurl: ""

remote_theme: pages-themes/minimal@v0.2.0


plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

